// packages/lit/src/components/l-table.ts
/**
 * Lit表格组件
 */

import { LitElement, html, css, type PropertyValues } from 'lit';
import { customElement, property, state, query } from 'lit/decorators.js';
import { classMap } from 'lit/directives/class-map.js';
import { styleMap } from 'lit/directives/style-map.js';
import {
  TableCore,
  type TableState,
  type RowData,
  type RowKey,
  type SortingState,
  type Column,
  getRowKey,
} from '@ldesign/table-core';
import '@ldesign/table-styles/src/index.css';

@customElement('l-table')
export class LTable<TData extends RowData = RowData> extends LitElement {
  // 样式
  static styles = css`
    :host {
      display: block;
      width: 100%;
    }
  `;

  // 属性
  @property({ type: Array }) data: TData[] = [];
  @property({ type: Array }) columns: any[] = [];
  @property({ type: String }) rowKey: keyof TData | string = 'id' as keyof TData;
  @property({ type: Number }) rowHeight = 48;
  @property({ type: Number }) headerHeight = 48;
  @property({ type: Boolean }) virtual = false;
  @property({ type: Boolean }) stripe = false;
  @property({ type: Boolean }) border = false;
  @property({ type: String }) selectionMode: 'single' | 'multiple' | 'false' = 'false';
  @property({ type: Boolean }) expandable = false;
  @property({ type: Boolean }) loading = false;

  // 内部状态
  @state() private tableState: TableState<TData> | null = null;

  // 引用
  @query('.l-table__container') private containerEl?: HTMLDivElement;

  private tableCore: TableCore<TData> | null = null;
  private resizeObserver: ResizeObserver | null = null;

  connectedCallback() {
    super.connectedCallback();
    this.initializeTable();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.destroyTable();
  }

  private initializeTable() {
    const selectionModeValue = this.selectionMode === 'false' ? false : this.selectionMode as 'single' | 'multiple';
    
    this.tableCore = new TableCore<TData>({
      data: this.data,
      columns: this.columns,
      rowKey: this.rowKey as any,
      rowHeight: this.rowHeight,
      headerHeight: this.headerHeight,
      virtual: this.virtual,
      selectionMode: selectionModeValue,
    });

    this.tableCore.subscribe((state) => {
      this.tableState = state;
    });
  }

  private destroyTable() {
    if (this.tableCore) {
      this.tableCore.destroy();
      this.tableCore = null;
    }

    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }
  }

  updated(changedProperties: PropertyValues) {
    if (changedProperties.has('data') && this.tableCore) {
      this.tableCore.setData(this.data);
    }

    if (this.virtual && this.containerEl && !this.resizeObserver && this.tableCore) {
      const { clientWidth, clientHeight } = this.containerEl;
      this.tableCore.setContainerSize(clientWidth, clientHeight);

      this.resizeObserver = new ResizeObserver((entries) => {
        for (const entry of entries) {
          const { width, height } = entry.contentRect;
          this.tableCore?.setContainerSize(width, height);
        }
      });

      this.resizeObserver.observe(this.containerEl);
    }
  }

  private getRowKeyValue(row: TData, index: number): RowKey {
    return getRowKey(row, this.rowKey as any, index);
  }

  private getColumnStyle(column: Column<TData>) {
    const style: any = {
      width: `${column.computedWidth}px`,
    };

    if (column.fixed === 'left' || column.fixed === 'right') {
      style[column.fixed] = `${column.fixedOffset}px`;
    }

    return style;
  }

  private getCellValue(row: TData, column: Column<TData>) {
    if (column.prop) {
      return row[column.prop];
    }
    return '';
  }

  private formatCellValue(row: TData, column: Column<TData>, rowIndex: number) {
    const value = this.getCellValue(row, column);
    if (column.formatter) {
      return column.formatter(value, row, rowIndex);
    }
    return value;
  }

  private isRowSelected(row: TData, index: number): boolean {
    if (!this.tableState) return false;
    const key = this.getRowKeyValue(row, index);
    return this.tableState.selection.selectedRowKeys.has(key);
  }

  private isRowExpanded(row: TData, index: number): boolean {
    if (!this.tableState) return false;
    const key = this.getRowKeyValue(row, index);
    return this.tableState.expand.expandedRowKeys.has(key);
  }

  private isSorting(columnId: string): boolean {
    if (!this.tableState) return false;
    return this.tableState.sorting.some((s) => s.id === columnId);
  }

  private getSortOrder(columnId: string): 'asc' | 'desc' | null {
    if (!this.tableState) return null;
    const sort = this.tableState.sorting.find((s) => s.id === columnId);
    return sort?.order ?? null;
  }

  private handleSelectAll() {
    this.tableCore?.toggleSelectAll();
    this.dispatchEvent(
      new CustomEvent('selection-change', {
        detail: {
          selectedKeys: Array.from(this.tableState?.selection.selectedRowKeys ?? []),
          selectedRows: this.tableCore?.getSelectedRows() ?? [],
        },
      })
    );
  }

  private handleRowSelect(row: TData, index: number) {
    const key = this.getRowKeyValue(row, index);
    this.tableCore?.toggleRowSelection(key);
    this.dispatchEvent(
      new CustomEvent('selection-change', {
        detail: {
          selectedKeys: Array.from(this.tableState?.selection.selectedRowKeys ?? []),
          selectedRows: this.tableCore?.getSelectedRows() ?? [],
        },
      })
    );
  }

  private handleRowExpand(row: TData, index: number) {
    const key = this.getRowKeyValue(row, index);
    this.tableCore?.toggleRowExpand(key);
  }

  private handleSort(columnId: string) {
    if (!this.tableCore || !this.tableState) return;
    const currentSort = this.tableState.sorting.find((s) => s.id === columnId);
    let newSorting: SortingState = [];

    if (!currentSort) {
      newSorting = [{ id: columnId, order: 'asc' }];
    } else if (currentSort.order === 'asc') {
      newSorting = [{ id: columnId, order: 'desc' }];
    }

    this.tableCore.setSorting(newSorting);
    this.dispatchEvent(
      new CustomEvent('sort-change', {
        detail: { sorting: newSorting },
      })
    );
  }

  private handleScroll(event: Event) {
    if (!this.virtual || !this.tableCore) return;
    const target = event.target as HTMLDivElement;
    this.tableCore.setScrollTop(target.scrollTop);
    this.tableCore.setScrollLeft(target.scrollLeft);
  }

  render() {
    if (!this.tableState) return html``;

    const flatColumns = this.tableState.columns;
    const displayData = this.virtual && this.tableState.virtualScroll
      ? this.tableState.processedData.slice(
          this.tableState.virtualScroll.visibleRowRange.start,
          this.tableState.virtualScroll.visibleRowRange.end
        )
      : this.tableState.processedData;

    const startIndex = this.virtual && this.tableState.virtualScroll
      ? this.tableState.virtualScroll.visibleRowRange.start
      : 0;

    const totalHeight = this.virtual
      ? this.tableState.processedData.length * this.rowHeight + this.headerHeight
      : 0;

    const bodyStyle = this.virtual && this.tableState.virtualScroll
      ? { transform: `translateY(${this.tableState.virtualScroll.visibleRowRange.start * this.rowHeight}px)` }
      : {};

    const columnCount =
      flatColumns.length +
      (this.selectionMode !== 'false' ? 1 : 0) +
      (this.expandable ? 1 : 0);

    const isAllSelected = this.tableState.processedData.length > 0 &&
      this.tableState.processedData.every((row, index) => {
        const key = this.getRowKeyValue(row, index);
        return this.tableState!.selection.selectedRowKeys.has(key);
      });

    const isIndeterminate = (() => {
      const selectedCount = this.tableState.processedData.filter((row, index) => {
        const key = this.getRowKeyValue(row, index);
        return this.tableState!.selection.selectedRowKeys.has(key);
      }).length;
      return selectedCount > 0 && selectedCount < this.tableState.processedData.length;
    })();

    return html`
      <div
        class=${classMap({
          'l-table': true,
          'l-table--stripe': this.stripe,
          'l-table--border': this.border,
          'l-table--virtual': this.virtual,
        })}
      >
        <div class="l-table__wrapper">
          <div
            class="l-table__container"
            @scroll=${this.handleScroll}
          >
            ${this.virtual
              ? html`<div
                  class="l-table__virtual-spacer"
                  style=${styleMap({ height: `${totalHeight}px` })}
                ></div>`
              : ''}

            <table class="l-table__table">
              <!-- 表头 -->
              <thead class="l-table__header">
                <tr class="l-table__header-row">
                  ${this.selectionMode !== 'false'
                    ? html`<th
                        class="l-table__header-cell l-table__header-cell--center"
                        style="width: 48px"
                      >
                        ${this.selectionMode === 'multiple'
                          ? html`<div class="l-table__selection">
                              <label class="l-table__checkbox">
                                <input
                                  type="checkbox"
                                  class="l-table__checkbox-input"
                                  .checked=${isAllSelected}
                                  .indeterminate=${isIndeterminate}
                                  @change=${this.handleSelectAll}
                                />
                                <span class="l-table__checkbox-inner"></span>
                              </label>
                            </div>`
                          : ''}
                      </th>`
                    : ''}
                  
                  ${this.expandable
                    ? html`<th
                        class="l-table__header-cell l-table__header-cell--center"
                        style="width: 48px"
                      ></th>`
                    : ''}

                  ${flatColumns.map(
                    (column) => html`
                      <th
                        class=${classMap({
                          'l-table__header-cell': true,
                          [`l-table__header-cell--${column.align}`]: true,
                          'l-table__header-cell--sortable': column.sortable,
                          'l-table__header-cell--sorting': this.isSorting(column.id),
                          'l-table__header-cell--fixed-left': column.fixed === 'left',
                          'l-table__header-cell--fixed-right': column.fixed === 'right',
                        })}
                        style=${styleMap(this.getColumnStyle(column))}
                        @click=${column.sortable ? () => this.handleSort(column.id) : null}
                      >
                        <div class="l-table__header-cell-content">
                          ${column.label}
                          ${column.sortable
                            ? html`<span class="l-table__sort">
                                <i
                                  class=${classMap({
                                    'l-table__sort-icon': true,
                                    'l-table__sort-icon--asc': true,
                                    'is-active': this.getSortOrder(column.id) === 'asc',
                                  })}
                                ></i>
                                <i
                                  class=${classMap({
                                    'l-table__sort-icon': true,
                                    'l-table__sort-icon--desc': true,
                                    'is-active': this.getSortOrder(column.id) === 'desc',
                                  })}
                                ></i>
                              </span>`
                            : ''}
                        </div>
                      </th>
                    `
                  )}
                </tr>
              </thead>

              <!-- 表体 -->
              <tbody class="l-table__body" style=${styleMap(bodyStyle)}>
                ${displayData.length > 0
                  ? displayData.map((row, rowIndex) => {
                      const actualIndex = startIndex + rowIndex;

                      return html`
                        <tr
                          class=${classMap({
                            'l-table__body-row': true,
                            'l-table__body-row--selected': this.isRowSelected(row, actualIndex),
                          })}
                        >
                          ${this.selectionMode !== 'false'
                            ? html`<td class="l-table__body-cell l-table__body-cell--center">
                                <div class="l-table__selection">
                                  <label class="l-table__checkbox">
                                    <input
                                      type="checkbox"
                                      class="l-table__checkbox-input"
                                      .checked=${this.isRowSelected(row, actualIndex)}
                                      @change=${() => this.handleRowSelect(row, actualIndex)}
                                    />
                                    <span class="l-table__checkbox-inner"></span>
                                  </label>
                                </div>
                              </td>`
                            : ''}

                          ${this.expandable
                            ? html`<td class="l-table__body-cell l-table__body-cell--center">
                                <div
                                  class=${classMap({
                                    'l-table__expand': true,
                                    'l-table__expand--expanded': this.isRowExpanded(row, actualIndex),
                                  })}
                                  @click=${() => this.handleRowExpand(row, actualIndex)}
                                >
                                  <i class="l-table__expand-icon"></i>
                                </div>
                              </td>`
                            : ''}

                          ${flatColumns.map(
                            (column) => html`
                              <td
                                class=${classMap({
                                  'l-table__body-cell': true,
                                  [`l-table__body-cell--${column.align}`]: true,
                                  'l-table__body-cell--fixed-left': column.fixed === 'left',
                                  'l-table__body-cell--fixed-right': column.fixed === 'right',
                                })}
                                style=${styleMap(this.getColumnStyle(column))}
                              >
                                ${this.formatCellValue(row, column, actualIndex)}
                              </td>
                            `
                          )}
                        </tr>

                        ${this.expandable && this.isRowExpanded(row, actualIndex)
                          ? html`<tr class="l-table__expand-row">
                              <td colspan=${columnCount} class="l-table__expand-cell">
                                <div class="l-table__expand-content">
                                  <slot name="expand" .row=${row} .rowIndex=${actualIndex}></slot>
                                </div>
                              </td>
                            </tr>`
                          : ''}
                      `;
                    })
                  : html`<tr>
                      <td colspan=${columnCount} class="l-table__empty">
                        <slot name="empty">
                          <div class="l-table__empty-text">暂无数据</div>
                        </slot>
                      </td>
                    </tr>`}
              </tbody>
            </table>
          </div>
        </div>

        ${this.loading
          ? html`<div class="l-table__loading">
              <slot name="loading">
                <div class="l-table__loading-text">加载中...</div>
              </slot>
            </div>`
          : ''}
      </div>
    `;
  }

  // 公共方法
  public getSelectedRows(): TData[] {
    return this.tableCore?.getSelectedRows() ?? [];
  }

  public clearSelection(): void {
    this.tableCore?.toggleSelectAll();
  }

  public exportData(options: any): void {
    this.tableCore?.exportData(options);
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'l-table': LTable;
  }
}

// packages/vue/src/components/LTable.vue
<template>
  <div
    ref="tableRef"
    class="l-table"
    :class="tableClasses"
  >
    <div class="l-table__wrapper">
      <div
        ref="containerRef"
        class="l-table__container"
        @scroll="handleScroll"
      >
        <!-- 虚拟滚动占位 -->
        <div
          v-if="virtual"
          class="l-table__virtual-spacer"
          :style="{ height: `${totalHeight}px` }"
        />

        <table class="l-table__table" :style="tableStyle">
          <!-- 表头 -->
          <thead class="l-table__header">
            <tr class="l-table__header-row">
              <!-- 选择列 -->
              <th
                v-if="selectionMode"
                class="l-table__header-cell l-table__header-cell--center"
                :style="{ width: '48px' }"
              >
                <div class="l-table__selection" v-if="selectionMode === 'multiple'">
                  <label class="l-table__checkbox">
                    <input
                      type="checkbox"
                      class="l-table__checkbox-input"
                      :checked="isAllSelected"
                      :indeterminate="isIndeterminate"
                      @change="handleSelectAll"
                    />
                    <span class="l-table__checkbox-inner"></span>
                  </label>
                </div>
              </th>

              <!-- 展开列 -->
              <th
                v-if="expandable"
                class="l-table__header-cell l-table__header-cell--center"
                :style="{ width: '48px' }"
              >
              </th>

              <!-- 数据列 -->
              <th
                v-for="column in flatColumns"
                :key="column.id"
                class="l-table__header-cell"
                :class="[
                  `l-table__header-cell--${column.align}`,
                  {
                    'l-table__header-cell--sortable': column.sortable,
                    'l-table__header-cell--sorting': isSorting(column.id),
                    'l-table__header-cell--fixed-left': column.fixed === 'left',
                    'l-table__header-cell--fixed-right': column.fixed === 'right',
                  }
                ]"
                :style="getColumnStyle(column)"
                @click="column.sortable && handleSort(column.id)"
              >
                <div class="l-table__header-cell-content">
                  <slot :name="`header-${column.id}`" :column="column">
                    {{ column.label }}
                  </slot>
                  
                  <!-- 排序图标 -->
                  <span v-if="column.sortable" class="l-table__sort">
                    <i
                      class="l-table__sort-icon l-table__sort-icon--asc"
                      :class="{ 'is-active': getSortOrder(column.id) === 'asc' }"
                    ></i>
                    <i
                      class="l-table__sort-icon l-table__sort-icon--desc"
                      :class="{ 'is-active': getSortOrder(column.id) === 'desc' }"
                    ></i>
                  </span>
                </div>

                <!-- 列宽调整 -->
                <div
                  v-if="column.resizable"
                  class="l-table__resize-handle"
                  @mousedown="handleResizeStart($event, column.id)"
                ></div>
              </th>
            </tr>
          </thead>

          <!-- 表体 -->
          <tbody class="l-table__body" :style="bodyStyle">
            <template v-if="displayData.length > 0">
              <template
                v-for="(row, rowIndex) in displayData"
                :key="getRowKeyValue(row, startIndex + rowIndex)"
              >
                <!-- 主行 -->
                <tr
                  class="l-table__body-row"
                  :class="{
                    'l-table__body-row--selected': isRowSelected(row, startIndex + rowIndex)
                  }"
                  @click="handleRowClick(row, startIndex + rowIndex, $event)"
                >
                  <!-- 选择列 -->
                  <td
                    v-if="selectionMode"
                    class="l-table__body-cell l-table__body-cell--center"
                  >
                    <div class="l-table__selection">
                      <label class="l-table__checkbox">
                        <input
                          type="checkbox"
                          class="l-table__checkbox-input"
                          :checked="isRowSelected(row, startIndex + rowIndex)"
                          @change="handleRowSelect(row, startIndex + rowIndex)"
                        />
                        <span class="l-table__checkbox-inner"></span>
                      </label>
                    </div>
                  </td>

                  <!-- 展开列 -->
                  <td
                    v-if="expandable"
                    class="l-table__body-cell l-table__body-cell--center"
                  >
                    <div
                      class="l-table__expand"
                      :class="{ 'l-table__expand--expanded': isRowExpanded(row, startIndex + rowIndex) }"
                      @click.stop="handleRowExpand(row, startIndex + rowIndex)"
                    >
                      <i class="l-table__expand-icon"></i>
                    </div>
                  </td>

                  <!-- 数据列 -->
                  <td
                    v-for="column in flatColumns"
                    :key="column.id"
                    class="l-table__body-cell"
                    :class="[
                      `l-table__body-cell--${column.align}`,
                      {
                        'l-table__body-cell--fixed-left': column.fixed === 'left',
                        'l-table__body-cell--fixed-right': column.fixed === 'right',
                      }
                    ]"
                    :style="getColumnStyle(column)"
                    @click="handleCellClick(row, column, startIndex + rowIndex, $event)"
                  >
                    <slot
                      :name="`cell-${column.id}`"
                      :row="row"
                      :column="column"
                      :rowIndex="startIndex + rowIndex"
                      :value="getCellValue(row, column)"
                    >
                      {{ formatCellValue(row, column, startIndex + rowIndex) }}
                    </slot>
                  </td>
                </tr>

                <!-- 展开行 -->
                <tr
                  v-if="expandable && isRowExpanded(row, startIndex + rowIndex)"
                  class="l-table__expand-row"
                >
                  <td
                    :colspan="columnCount"
                    class="l-table__expand-cell"
                  >
                    <div class="l-table__expand-content">
                      <slot
                        name="expand"
                        :row="row"
                        :rowIndex="startIndex + rowIndex"
                      ></slot>
                    </div>
                  </td>
                </tr>
              </template>
            </template>

            <!-- 空状态 -->
            <tr v-else>
              <td :colspan="columnCount" class="l-table__empty">
                <slot name="empty">
                  <div class="l-table__empty-text">暂无数据</div>
                </slot>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- 加载状态 -->
    <div v-if="loading" class="l-table__loading">
      <slot name="loading">
        <div class="l-table__loading-text">加载中...</div>
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts" generic="TData extends RowData">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import type { RowData, RowKey, SortingState, Column } from '@ldesign/table-core';
import { useTable } from '../composables/useTable';
import { getRowKey } from '@ldesign/table-core';

// Props
const props = withDefaults(
  defineProps<{
    data: TData[];
    columns: any[];
    rowKey?: keyof TData | ((row: TData) => RowKey);
    rowHeight?: number;
    headerHeight?: number;
    virtual?: boolean;
    stripe?: boolean;
    border?: boolean;
    selectionMode?: 'single' | 'multiple' | false;
    expandable?: boolean;
    loading?: boolean;
    height?: number | string;
  }>(),
  {
    rowKey: 'id' as any,
    rowHeight: 48,
    headerHeight: 48,
    virtual: false,
    stripe: false,
    border: false,
    selectionMode: false,
    expandable: false,
    loading: false,
  }
);

// Emits
const emit = defineEmits<{
  'selection-change': [selectedKeys: RowKey[], selectedRows: TData[]];
  'sort-change': [sorting: SortingState];
  'row-click': [row: TData, rowIndex: number, event: Event];
  'cell-click': [row: TData, column: Column<TData>, rowIndex: number, event: Event];
}>();

// Refs
const tableRef = ref<HTMLDivElement>();
const containerRef = ref<HTMLDivElement>();

// 使用表格核心
const { state, tableCore } = useTable<TData>({
  data: props.data,
  columns: props.columns,
  rowKey: props.rowKey,
  rowHeight: props.rowHeight,
  headerHeight: props.headerHeight,
  virtual: props.virtual,
  selectionMode: props.selectionMode,
});

// 计算属性
const tableClasses = computed(() => [
  {
    'l-table--stripe': props.stripe,
    'l-table--border': props.border,
    'l-table--virtual': props.virtual,
  },
]);

const flatColumns = computed(() => state.value.columns);

const columnCount = computed(() => {
  let count = flatColumns.value.length;
  if (props.selectionMode) count++;
  if (props.expandable) count++;
  return count;
});

const displayData = computed(() => {
  if (props.virtual && state.value.virtualScroll) {
    const { start, end } = state.value.virtualScroll.visibleRowRange;
    return state.value.processedData.slice(start, end);
  }
  return state.value.processedData;
});

const startIndex = computed(() => {
  if (props.virtual && state.value.virtualScroll) {
    return state.value.virtualScroll.visibleRowRange.start;
  }
  return 0;
});

const totalHeight = computed(() => {
  if (props.virtual && state.value.virtualScroll) {
    return state.value.processedData.length * props.rowHeight + props.headerHeight;
  }
  return 0;
});

const bodyStyle = computed(() => {
  if (props.virtual && state.value.virtualScroll) {
    const offset = state.value.virtualScroll.visibleRowRange.start * props.rowHeight;
    return {
      transform: `translateY(${offset}px)`,
    };
  }
  return {};
});

const tableStyle = computed(() => {
  if (props.height) {
    return {
      height: typeof props.height === 'number' ? `${props.height}px` : props.height,
    };
  }
  return {};
});

const isAllSelected = computed(() => {
  const data = state.value.processedData;
  if (data.length === 0) return false;
  return data.every((row, index) => {
    const key = getRowKeyValue(row, index);
    return state.value.selection.selectedRowKeys.has(key);
  });
});

const isIndeterminate = computed(() => {
  const data = state.value.processedData;
  const selectedCount = data.filter((row, index) => {
    const key = getRowKeyValue(row, index);
    return state.value.selection.selectedRowKeys.has(key);
  }).length;
  return selectedCount > 0 && selectedCount < data.length;
});

// 方法
function getRowKeyValue(row: TData, index: number): RowKey {
  return getRowKey(row, props.rowKey, index);
}

function getColumnStyle(column: Column<TData>) {
  const style: any = {
    width: `${column.computedWidth}px`,
  };

  if (column.fixed === 'left' || column.fixed === 'right') {
    style[column.fixed] = `${column.fixedOffset}px`;
  }

  return style;
}

function getCellValue(row: TData, column: Column<TData>) {
  if (column.prop) {
    return row[column.prop];
  }
  return null;
}

function formatCellValue(row: TData, column: Column<TData>, rowIndex: number) {
  const value = getCellValue(row, column);
  if (column.formatter) {
    return column.formatter(value, row, rowIndex);
  }
  return value;
}

function isRowSelected(row: TData, index: number): boolean {
  const key = getRowKeyValue(row, index);
  return state.value.selection.selectedRowKeys.has(key);
}

function isRowExpanded(row: TData, index: number): boolean {
  const key = getRowKeyValue(row, index);
  return state.value.expand.expandedRowKeys.has(key);
}

function isSorting(columnId: string): boolean {
  return state.value.sorting.some((s) => s.id === columnId);
}

function getSortOrder(columnId: string): 'asc' | 'desc' | null {
  const sort = state.value.sorting.find((s) => s.id === columnId);
  return sort?.order ?? null;
}

function handleSelectAll() {
  tableCore.toggleSelectAll();
  emit('selection-change', Array.from(state.value.selection.selectedRowKeys), tableCore.getSelectedRows());
}

function handleRowSelect(row: TData, index: number) {
  const key = getRowKeyValue(row, index);
  tableCore.toggleRowSelection(key);
  emit('selection-change', Array.from(state.value.selection.selectedRowKeys), tableCore.getSelectedRows());
}

function handleRowExpand(row: TData, index: number) {
  const key = getRowKeyValue(row, index);
  tableCore.toggleRowExpand(key);
}

function handleSort(columnId: string) {
  const currentSort = state.value.sorting.find((s) => s.id === columnId);
  let newSorting: SortingState = [];

  if (!currentSort) {
    newSorting = [{ id: columnId, order: 'asc' }];
  } else if (currentSort.order === 'asc') {
    newSorting = [{ id: columnId, order: 'desc' }];
  } else {
    // 清除排序
    newSorting = [];
  }

  tableCore.setSorting(newSorting);
  emit('sort-change', newSorting);
}

function handleScroll(event: Event) {
  const target = event.target as HTMLDivElement;
  if (props.virtual) {
    tableCore.setScrollTop(target.scrollTop);
    tableCore.setScrollLeft(target.scrollLeft);
  }
}

function handleRowClick(row: TData, rowIndex: number, event: Event) {
  emit('row-click', row, rowIndex, event);
}

function handleCellClick(row: TData, column: Column<TData>, rowIndex: number, event: Event) {
  emit('cell-click', row, column, rowIndex, event);
}

// 列宽调整
let resizingColumn: string | null = null;
let resizeStartX = 0;
let resizeStartWidth = 0;

function handleResizeStart(event: MouseEvent, columnId: string) {
  event.stopPropagation();
  const column = flatColumns.value.find((c) => c.id === columnId);
  if (!column) return;

  resizingColumn = columnId;
  resizeStartX = event.clientX;
  resizeStartWidth = column.computedWidth;

  document.addEventListener('mousemove', handleResizeMove);
  document.addEventListener('mouseup', handleResizeEnd);
}

function handleResizeMove(event: MouseEvent) {
  if (!resizingColumn) return;

  const diff = event.clientX - resizeStartX;
  const newWidth = resizeStartWidth + diff;

  tableCore.resizeColumn(resizingColumn, newWidth);
}

function handleResizeEnd() {
  resizingColumn = null;
  document.removeEventListener('mousemove', handleResizeMove);
  document.removeEventListener('mouseup', handleResizeEnd);
}

// 生命周期
onMounted(() => {
  if (props.virtual && containerRef.value) {
    const { clientWidth, clientHeight } = containerRef.value;
    tableCore.setContainerSize(clientWidth, clientHeight);

    // 监听容器尺寸变化
    const resizeObserver = new ResizeObserver((entries) => {
      for (const entry of entries) {
        const { width, height } = entry.contentRect;
        tableCore.setContainerSize(width, height);
      }
    });

    resizeObserver.observe(containerRef.value);

    onUnmounted(() => {
      resizeObserver.disconnect();
    });
  }
});

// 监听数据变化
watch(
  () => props.data,
  (newData) => {
    tableCore.setData(newData);
  },
  { deep: true }
);

// 暴露方法给父组件
defineExpose({
  getSelectedRows: () => tableCore.getSelectedRows(),
  clearSelection: () => tableCore.toggleSelectAll(),
  exportData: tableCore.exportData.bind(tableCore),
});
</script>
